@echo off
rem Generated by JetBrains Toolbox 1.25.12424 at 2022-07-11T15:31:55.805456

set waitarg=
set ideargs=

:next
set "passwait="
if "%~1"=="--wait" set passwait=1
if "%~1"=="-w" set passwait=1
if defined passwait (set waitarg=/wait)
if not "%~1"=="" (
  if defined passwait (set "ideargs=%ideargs%--wait ") else (set "ideargs=%ideargs%%1 ")
  shift
  goto next
)

start "" %waitarg% C:\Users\henri\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\221.5787.36\bin\rider64.exe %ideargs%